heat_template_version: 2013-05-23

description: >
  This pattern deploys a single virtual machine in the cloud.
parameters:
  flavor:
    type: string
    description: Flavor to be used for compute instance
  key_name:
    type: string
    description: Name of the key-pair to be used for the compute instance
  availability_zone:
    type: string
    description: Name of availability zone in which to create the instance
  private_network_id:
    type: string
    description: Private network to attach to compute instance
  name:
    type: string
    description: Name of the compute instance
  image:
    type: string
    description: Name of the image to create the compute instance

resources:
  single_vm:
    type: OS::Nova::Server
    properties:
      networks:
          - port: { get_resource: private_network_id_port  }
      name: { get_param: name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      availability_zone: { get_param: availability_zone }


  private_network_id_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_network_id }
